# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: src/generic
project_affiliation: SDSC-ORDES
project_authors:
-   email: laure.vancauwenberghe@epfl.ch
    first_name: Laure
    last_name: Vancauwenberghe
-   email: cyril.matthey-doret@epfl.ch
    first_name: Cyril
    last_name: Matthey-Doret
project_description: Helm charts for projects of the ORD team at SDSC
project_hosts:
-   host: github.com
    organization: sdsc-ordes
    repo: helm-charts
project_language: generic
project_license: apache2
project_name: helm charts
project_url: https://github.com/sdsc-ordes/helm-charts
project_version: 0.0.1
